parameters:
  path.schema: '%root_path%/config/schema.json'

services:
  serializer:
    class: '\JMS\Serializer\SerializerInterface'
    factory: ['\Alberteddu\Octopus\Serializer\SerializerBuilder', createOctopusSerializer]

  parser:
    class: '\Alberteddu\Octopus\Parser\Parser'

  builder:
    class: '\Alberteddu\Octopus\Builder\Builder'
    arguments: ['@parser', '@validator', '@render']

  validator:
    class: '\Alberteddu\Octopus\Validator\Validator'
    arguments: ['@validator.schema']

  validator.schema:
    class: 'JsonSchema\Validator'

  render:
    class: '\Alberteddu\Octopus\Render\Render'
